.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. oduwausd_coin_qt test_oduwausd_coin_qt
clean: FORCE
	$(MAKE) -C .. oduwausd_coin_qt_clean test_oduwausd_coin_qt_clean
check: FORCE
	$(MAKE) -C .. test_oduwausd_coin_qt_check
oduwausd_coin-qt oduwausd_coin-qt.exe: FORCE
	 $(MAKE) -C .. oduwausd_coin_qt
